apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: judge0
  template:
    metadata:
      labels:
        app: judge0
    spec:
      containers:
      - name: judge0
        image: judge0/judge0:latest
        ports:
        - containerPort: 2358
---

apiVersion: v1
kind: Service
metadata:
  name: judge0-service
spec:
  selector:
    app: judge0
  ports:
  - protocol: TCP
    port: 2358
    targetPort: 2358
  type: NodePort